### ISSUE TITLE
Scripts not working with Scapy v2.4.2

### ISSUE THREAD

**Issue by adriangranados** [adriangranados/wifiexplorer-sensor#1]
The scripts breaks after updating to Scapy v2.4.2 with the following exception:

    wlanpi@wlanpi:~/wifiexplorer-sensor$ cat /tmp/wifiexplorer-sensor.log
    Exception in thread Thread-1:
    Traceback (most recent call last):
     File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
       self.run()
     File "/usr/lib/python2.7/threading.py", line 754, in run
       self.__target(*self.__args, **self.__kwargs)
     File "/usr/local/bin/wifiexplorer-sensor.py", line 85, in packet_sniffer
       sniff(iface=interface, prn=packet_handler, store=0, timeout=3)
     File "/usr/local/lib/python2.7/dist-packages/scapy-git_archive.devc5aefe757-py2.7.egg/scapy/sendrecv.py", line 886, in sniffer = prn(p)
     File "/usr/local/bin/wifiexplorer-sensor.py", line 76, in packet_handler
       bssid = p[Dot11].addr3
     File "/usr/local/lib/python2.7/dist-packages/scapy-git_archive.devc5aefe757-py2.7.egg/scapy/packet.py", line 1079, in __getitem__
       raise IndexError("Layer [%s] not found" % lname)
    IndexError: Layer [Dot11] not found`

**Comment by adriangranados** [comment]
It seems updating scapy using the distutils method breaks scapy. Updating scapy using the pip method works fine.
